Add invisible capatcha to user and partner form inscription #370
hostolab/covidliste pull request #380
Opened 2021-04-14 13:10 UTC by peiofour

Issue #370 

Ajout d'un captcha invisible pour bloquer les bots sur les formulaires d'inscription

2021-04-14 13:43 UTC, adrienpoly reviewed
Top cette gem

2021-04-14 13:43 UTC, adrienpoly commented on config/initializers/invisible_captcha.rb
> +  config.honeypots << ["more", "fake", "attribute", "names"]
Jamais utilisé cette gem, je me demandais s'il ne faut pas ici mettre des vrais nom de champs potentiels

cf : https://github.com/markets/invisible_captcha#plugin-options

top en tout cas

2021-04-14 13:43 UTC, adrienpoly commented on app/controllers/partners_controller.rb
> +  invisible_captcha only: %i[create update], honeypot: :subtitle
Peut etre uniquement sur le create?

l'update le user a déjà validé sont compte via l'email de confirmation cela me semble suffisant

2021-04-14 13:43 UTC, adrienpoly commented on app/controllers/users_controller.rb
> +  invisible_captcha only: %i[create update], honeypot: :subtitle
same same comment

2021-04-14 15:27 UTC, peiofour commented on config/initializers/invisible_captcha.rb
> +  config.honeypots << ["more", "fake", "attribute", "names"]
J'ai fait quelque recherche supplémentaire là, je vais enlever le honeypots en effet, on garde celui par default. Pour update également je fais un commit

2021-04-14 15:57 UTC, thbar requested changes
Quelques petits trucs pas clair (je renommerais "subtitle" dans quelque chose de plus custom), et je me pose la question de si c'est peu coûteux d'ajouter un petit test, ça pourrait être bien notamment pour quand on finira inévitablement par mettre à jour cette gem plus tard (ou Rails), car c'est une feature qui a de la valeur.

2021-04-14 15:57 UTC, thbar commented on app/controllers/partners_controller.rb
> +  invisible_captcha only: [:create], honeypot: :subtitle
Je me demande pourquoi il s'appelle `subtitle` ?

2021-04-14 15:57 UTC, thbar commented on app/controllers/partners_controller.rb
> +  invisible_captcha only: [:create], honeypot: :subtitle
Je vois sur https://github.com/markets/invisible_captcha#controller-method-options que c'est le nom proposé dans le readme par défaut.

2021-04-14 15:57 UTC, thbar commented on app/views/partners/new.html.erb
> +                <%= f.invisible_captcha :subtitle, honeypots: true%>
Pour référence, voir https://github.com/markets/invisible_captcha#plugin-options.

2021-04-14 18:52 UTC, peiofour commented on app/controllers/partners_controller.rb
> +  invisible_captcha only: [:create], honeypot: :subtitle
Oui j'ai gardé le même nom, je ne me suis pas embêté

2021-04-14 18:52 UTC, peiofour commented on app/views/partners/new.html.erb
> +                <%= f.invisible_captcha :subtitle, honeypots: true%>
same du coup, j'ai gardé le même nom par défaut

2021-04-15 13:07 UTC, mathieuripert commented
> Quelques petits trucs pas clair (je renommerais "subtitle" dans quelque chose de plus custom), et je me pose la question de si c'est peu coûteux d'ajouter un petit test, ça pourrait être bien notamment pour quand on finira inévitablement par mettre à jour cette gem plus tard (ou Rails), car c'est une feature qui a de la valeur.

+1 mais je pense qu'on peut merger sans le test pour le moment vu que c'était une issue p1

2021-04-15 13:07 UTC, merged