Partner profile like regular users
hostolab/covidliste pull request #463
Opened 2021-04-17 02:12 UTC by carsso

Fixes #453

Profil partenaire, comme pour les utilisateurs normaux.

<img width="1016" alt="Capture d’écran 2021-04-17 à 04 12 31" src="https://user-images.githubusercontent.com/666182/115098935-24886880-9f33-11eb-83e0-72f624294f2d.png">

2021-04-18 15:20 UTC, mathieuripert commented
Je pense pas qu'il y ait besoin de proposer la suppression d'un compte partenaire. Ca a été remonté côté supply ?

2021-04-18 15:49 UTC, mathieuripert requested changes
Est ce nécessaire ?

2021-04-18 18:50 UTC, carsso commented
C'est pour éviter de se taper la suppression manuelle des particuliers qui se plantent.
Et aussi réglementairement je suppose que ça facilite. cc @Florto

2021-04-18 18:52 UTC, Florto commented
En effet les pros ont droit à modification. Cela dit un pro devrait etre réapprouvé en cas de modif.

Donc juste bouton suppression et une notice contactez l'équipe ?

2021-04-18 19:00 UTC, carsso commented
Conflit fixé

2021-04-20 13:30 UTC, EmCousin commented on app/models/partner.rb
> +      csv << columns.map { |column| send(column) }
Il existe la methode `public_send` pour eval dynamiquement une méthode et retourner une erreur si celle-ci est privée.
À moins que tu cherches explicitement à appeler une méthode privée via `send`, je t'invite à utiliser `public_send` par défaut 🙂 

```suggestion
      csv << columns.map { |column| public_send(column) }
```

2021-04-21 15:36 UTC, EmCousin commented on config/routes.rb
> +  delete "/partners/profile" => "partners#delete", :as => ""
```suggestion
  resources :partners, only: [:new, :create] do
    resource :profile, only: %i[show update destroy]
  end
```

2021-04-21 15:36 UTC, EmCousin commented on config/routes.rb
> +  delete "/partners/profile" => "partners#delete", :as => ""
Par convention en Rails l'action REST pour supprimer une ressource est `destroy` plutôt que `delete`

2021-04-21 23:33 UTC, carsso commented
Changements suggérés faits, merci @EmCousin

2021-04-22 21:23 UTC, merged