Changing wording for campaign cancel
hostolab/covidliste pull request #465
Opened 2021-04-17 04:43 UTC by carsso

Début d'implémentation de #401

Interruption en cours
<img width="1191" alt="Capture d’écran 2021-04-17 à 06 34 13" src="https://user-images.githubusercontent.com/666182/115101921-1133c800-9f48-11eb-8d31-9c525ee3833a.png">

Interrompue manuellement
<img width="1156" alt="Capture d’écran 2021-04-17 à 06 34 39" src="https://user-images.githubusercontent.com/666182/115101922-12fd8b80-9f48-11eb-9956-6b2a15d1db37.png">

2021-04-17 19:32 UTC, mininao commented on app/models/campaign.rb
> +    updated_at + SendCampaignJob::BATCH_EXPIRE_IN_MINUTES.minutes + 1.minute > DateTime.now
Il faudrait pas aussi checker que `campaign.canceled?` ?

2021-04-17 19:50 UTC, mininao commented on app/models/campaign.rb
> +    updated_at + SendCampaignJob::BATCH_EXPIRE_IN_MINUTES.minutes + 1.minute > DateTime.now
En fait je trouve ça un peu chaud de se baser sur updated_at, si jamais on fait une feature plus tard qui modifie une campagne après sa cancellation, ça va casser ça.
A mon avis il faudrait introduire un canceled_at ?

2021-04-17 19:50 UTC, mininao commented on app/views/admin/vaccination_centers/show.html.erb
> +              <td> <%= campaign.matches.confirmed.size %> </td>
C'est quoi la différence entre size et count ?

2021-04-17 19:52 UTC, mininao commented on app/views/admin/vaccination_centers/show.html.erb
> +              <td> <%= l campaign.starts_at %> </td>
C'est quoi le `l` ? Est-ce qu'on voudrait pas plutôt l'afficher au format français `strftime('%d/%m/%Y')` ?

2021-04-17 19:53 UTC, carsso commented on app/models/campaign.rb
> +    updated_at + SendCampaignJob::BATCH_EXPIRE_IN_MINUTES.minutes + 1.minute > DateTime.now
Yep, j'ai fait un "quick-win" mais pour moi t'as clairement raison.

2021-04-17 19:53 UTC, carsso commented on app/views/admin/vaccination_centers/show.html.erb
> +              <td> <%= campaign.matches.confirmed.size %> </td>
c'est presque pareil, c'est juste pour uniformiser les deux tableaux :p

2021-04-17 19:54 UTC, carsso commented on app/views/admin/vaccination_centers/show.html.erb
> +              <td> <%= l campaign.starts_at %> </td>
l c'est pour avoir une date au format local, pareil pour uniformiser les deux tableaux. ça fait un truc style 10/11/2021 12h45

2021-04-17 19:55 UTC, mininao commented on app/views/partners/campaigns/show.html.erb
> +<% if @campaign.running? || (@campaign.canceled? && @campaign.canceling?) %>
Je pense qu'il faut que campaign.canceling ne renvoie true que quand la campaign est vraiment en cours d'annulation (et donc canceled? == true), c'est un peu misleading autrement non ?

2021-04-17 19:56 UTC, carsso commented on app/views/partners/campaigns/show.html.erb
> +<% if @campaign.running? || (@campaign.canceled? && @campaign.canceling?) %>
Yes, je regarde ça

2021-04-17 20:10 UTC, mininao reviewed
C'est bon pour moi overall, mais avant de merger:
* Je pense qu'il faut que `campaign.canceling?` ne soit true que quand la campagne est canceled, sinon c'est misleading
* Je pense que `canceling_delay` et `canceling` ne doivent pas utiliser `updated_at`, c'est trop risqué si un autre champ est changé par la suite

Peut-être qu'on pourrait avoir :
`fully_canceled`
`canceling`
`canceled (= fully_canceled || canceling)`
et
`minutes_until_fully_canceled`, pour avoir un naming un peu plus clair que `canceling_delay`

2021-04-17 20:11 UTC, mininao commented on app/models/campaign.rb
> +  def canceling_delay
Je trouve que le nom est pas super clair, quand je le lis j'ai l'impression que c'est juste la durée de `SendCampaignJob::BATCH_EXPIRE_IN_MINUTES`

2021-04-17 20:11 UTC, mininao commented on app/views/admin/vaccination_centers/show.html.erb
> +              <td> <%= l campaign.starts_at %> </td>
ah ok top 👍

2021-04-17 20:11 UTC, carsso commented on app/models/campaign.rb
> +  def canceling_delay
yep yep

2021-04-17 20:52 UTC, mininao commented on app/models/campaign.rb
> +  def canceled!
C'est chelou de l'appeler canceled et pas cancel, non ? #nitpick

2021-04-17 20:54 UTC, carsso commented on app/models/campaign.rb
> +  def canceled!
Bah ouais, pas moi qui ai choisi, ça prend le nom du state, moi je l'ai juste surchargée comme tu vois, je fais un super après

2021-04-17 21:00 UTC, mininao commented on app/models/campaign.rb
> +      (canceled_at + SendCampaignJob::BATCH_EXPIRE_IN_MINUTES.minutes + 1.minute - DateTime.now) / 60
Je suggèrerais de return la valeur précise ici, donc de pas ajouter 1 minute, surtout qu'on ajoute une autre minute dans `human_readable_minutes_until_fully_canceled`, ce qui commence à faire une grosse marge ?

2021-04-17 21:06 UTC, carsso commented on app/models/campaign.rb
> +      (canceled_at + SendCampaignJob::BATCH_EXPIRE_IN_MINUTES.minutes + 1.minute - DateTime.now) / 60
Dans human_readable_minutes_until_fully_canceled, en réalité on ajoute pas une minute, on corrige l'arrondi :) Sinon ça dit "Interruption en cours... (~ 0 min.)" c'est pas top pour un humain.

2021-04-17 21:11 UTC, mininao approved these changes
🚢 🚀

2021-04-17 21:28 UTC, mininao approved these changes

2021-04-18 15:28 UTC, mathieuripert commented on app/controllers/partners/campaigns_controller.rb
>          @campaign.canceled!
Je sais que c'était déjà là avant mais je me rend compte que qu'il aurait fallu nommer cette méthode `cancel!` et non `canceled!`

2021-04-18 15:29 UTC, mathieuripert commented on app/models/campaign.rb
> +  def canceled!
`cancel!`

2021-04-18 15:33 UTC, mathieuripert commented on app/models/campaign.rb
> +  def minutes_until_fully_canceled
Je ne pense pas qu'il y a besoin d'introduire cette variable. 
Selon moi, dès que la campagne est annulée:
- il faut empêcher la creation de nouveau matches
- on peut afficher campagne annulée (ou interrompue) mais en disant qu'il y a encore X matches pending, et que le dernier match expire dans X minutes.

2021-04-18 15:47 UTC, mathieuripert requested changes
Je pense qu'on peut simplifier en ne gardant que le status = "Terminée" et n'affichant un warning `"#{matches.pending.count} personnes peuvent encore confirmer jusqu'à #{matches.pending.maximum(:expires_at)}"`

2021-04-18 21:46 UTC, carsso commented
Done, a part les noms des champs de l'enum que j'ai pas changé.

2021-04-18 21:58 UTC, carsso commented
Done, a part les noms des champs de l'enum que j'ai pas changé.

2021-04-20 08:44 UTC, mathieuripert commented on app/views/partners/campaigns/show.html.erb
> +  <% elsif @campaign.canceled? && @campaign.matches&.pending&.maximum(:expires_at) %>
```suggestion
  <% elsif @campaign.canceled? && @campaign.matches&.pending.any? %>
```

2021-04-20 08:45 UTC, mathieuripert commented on app/views/partners/campaigns/show.html.erb
> +  <% elsif @campaign.canceled? && @campaign.matches&.pending&.maximum(:expires_at) %>
mais ça marche aussi ce que tu as

2021-04-20 08:51 UTC, merged