Send anonymisation notice email
hostolab/covidliste pull request #550
Opened 2021-04-23 20:47 UTC by yann120

Related to issue #300 

- [x] On veut envoyer un mail aux volontaires après vaccination pour les remercier et leur dire qu'on va anonymiser leur données
- [x] Utilisation du mailer existant
- [x] Il faut que dans le cronjob on appelle le mailer
- [x] Il faut checker le contenu du mail, voir entre autres si on dit bien que le délai d'anonymisation et de 7j et non pas 24h

2021-04-23 23:49 UTC, navidemad commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +    users_to_anonymize.each do |user|
Si il y a bcp de users_to_anonymize peut-être faire un find_each.

2021-04-23 23:50 UTC, navidemad commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      MatchMailer.with(match: user.matches.first).send_anonymisation_notice.deliver_now
deliver_later peut-être pour éviter de surcharger ?

2021-04-24 10:51 UTC, yann120 commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      MatchMailer.with(match: user.matches.first).send_anonymisation_notice.deliver_now
Yes bonne idée!

2021-04-24 11:00 UTC, yann120 commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +    users_to_anonymize.each do |user|
find_each il faudrait le faire directement sur la query, non ?
Sachant qu'on a déjà fait la query dans la methode en dessous 
Ou alors on peut revoir cette query ?

2021-04-24 11:01 UTC, yann120 commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      MatchMailer.with(match: user.matches.first).send_anonymisation_notice.deliver_now
```suggestion
      MatchMailer.with(match: user.matches.first).send_anonymisation_notice.deliver_later
```

2021-04-24 11:17 UTC, navidemad commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +    users_to_anonymize.each do |user|
Bien vu, yes :find_each doit être fait sur un objet de type ActiveRelation et pas sur un objet de type Array.

2021-04-24 13:48 UTC, GuillaumeWrobel reviewed
:+1:

2021-04-24 13:48 UTC, GuillaumeWrobel commented on app/views/match_mailer/send_anonymisation_notice.html.erb
> +    Par ailleurs, nous avons bien supprimé vos données comme indiqué précédemment. À des fins statistiques, comme prévu par nos CGU, des informations anonymisées ne permettant ni de vous identifier n
:writing_hand: typo

```suggestion
    Par ailleurs, nous avons bien supprimé vos données comme indiqué précédemment. À des fins statistiques, comme prévu par nos CGU, des informations anonymisées ne permettant ni de vous identifier ni de vous contacter peuvent être conservées.
```

2021-04-24 13:48 UTC, GuillaumeWrobel commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +    users_to_anonymize.each do |user|
`users_to_anonymize` n'est-il pas déjà une `ActiveRelation` ? C'est un `Array` ?

2021-04-24 15:06 UTC, yann120 commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +    users_to_anonymize.each do |user|
Oui exact, mais la query est déjà faite, non ?
Le but de `find_each`serait de faire la query par batch de 1000 non ?
Je vais essayer de jouer avec ce soir en rentrant 🙂

2021-04-24 18:41 UTC, yann120 commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +    users_to_anonymize.each do |user|
Ok bon j'ai essayé en console le code, ça fonctionne bien avec le find_each 👍🏻 
Aucune idée si ça augmente la perf par contre

2021-04-24 18:41 UTC, yann120 commented on app/views/match_mailer/send_anonymisation_notice.html.erb
> +    Par ailleurs, nous avons bien supprimé vos données comme indiqué précédemment. À des fins statistiques, comme prévu par nos CGU, des informations anonymisées ne permettant ni de vous identifier n
Merci!

2021-04-24 21:24 UTC, mathieuripert commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      user.anonymize!
Ne faudrait il pas envoyer l'email avant d'anonymiser le user? Car au moment de l'anonymisation on perd l'email, du coup pas sûr que le mailer puisse envoyer l'email à la bonne adresse. A moins que le user soit correctement pre-loadé dans le match qui passe au mailer, mais je ne crois pas.

2021-04-25 08:29 UTC, yann120 commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      user.anonymize!
Ah oui c'est pas faux ça! 
Je vais essayer en console, et si c'est pas ok, je préfère stocker l'email dans une variable temporaire : comme ça on envoie le mail seulement quand l'utilisateur est supprimé 
Sinon c'est un peu mensonger de dire "on a bien supprimé vos données"
Qu'en penses-tu ?

2021-04-25 08:48 UTC, mathieuripert commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      user.anonymize!
Parfait ça !
Le mailer peut prendre comme argument uniquement un e-mail

2021-04-25 20:28 UTC, yann120 commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      user.anonymize!
Cool Merci @mathieuripert! Ma feature était bien cassée...
Le mail s'envoyait a un email anonymisé avec un prénom "Anonymous" 😆 

J'ai changé un peu la méthode du mailer pour qu'elle puisse prendre soit un match, soit un user.
J'ai hésité a tout changer pour qu'elle prenne qu'un user, mais j'étais pas sûr...

2021-04-26 23:10 UTC, navidemad requested changes
Quand on voit le mailer, on fait référence à l'utilisateur uniquement pour le Bonjour <....>.
De ce fait, je suis pas fan de faire une action de .dup pour ça.
De plus, passer un objet ActiveRecord au mailer va procéder à une sérialisation de l'objet.
Je stockerai juste une variable appellé user_email que je transmettrais au mailer.
Et je mettrais juste dans le mail:
Bonjour,

2021-04-26 23:10 UTC, navidemad commented on app/views/match_mailer/send_anonymisation_notice.html.erb
> +    Bonjour <%= @user %>,
```suggestion
    Bonjour,
```

2021-04-26 23:10 UTC, navidemad commented on app/mailers/match_mailer.rb
> +    @user = params[:user] || @match.user
```suggestion
    user_email = params[:user_email] || @match&.user&.email
```

2021-04-26 23:10 UTC, navidemad commented on app/mailers/match_mailer.rb
> +    return if @user.blank?
```suggestion
    return if user_email.blank?
```

2021-04-26 23:10 UTC, navidemad commented on app/mailers/match_mailer.rb
> +      to: @user.email,
```suggestion
      to: user_email,
```

2021-04-26 23:10 UTC, navidemad commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      MatchMailer.with(user: user).send_anonymisation_notice.deliver_later
```suggestion
      MatchMailer.with(user_email: user_email).send_anonymisation_notice.deliver_later
```

2021-04-26 23:10 UTC, navidemad commented on app/jobs/anonymize_confirmed_matched_users_job.rb
> +      user = user_to_anonymize.dup
```suggestion
      user_email = user_to_anonymize.email
```

2021-04-27 07:18 UTC, mathieuripert commented on app/mailers/match_mailer.rb
> +    @user = params[:user] || @match.user
Oui je pense qu'on peut se contenter de l'email

2021-04-27 07:19 UTC, merged