Add visible and media option in vaccination center
hostolab/covidliste pull request #623
Opened 2021-04-27 22:00 UTC by peiofour

Issue #473

2021-04-27 22:05 UTC, carsso approved these changes

2021-04-28 06:29 UTC, mathieuripert commented
> Issue #473

Merci @peiofour 

Je ne suis pas sûr qu'on ait besoin des deux champs (boolean et datetime) pour chaque field. A mon avis, le champs datetime suffit.

Aussi, le naming proposé était `media_optin_at` et `visible_optin_at` pour `opt-tin` 😛

2021-04-28 06:29 UTC, mathieuripert requested changes
voir ci-dessus

2021-04-28 07:28 UTC, peiofour commented
Ok, je regarde ça ce soir.

2021-04-29 09:22 UTC, Intrepidd reviewed
D'après le ticket : 

> Il faut qu'ils puissent changer ça a tout moment dans l'espace partenaires.

J'ai l'impression que ce n'est pas le cas ici ? On devrait également gérer edit / update n'est-ce pas ?

2021-05-04 19:31 UTC, genezys commented on app/controllers/partners/vaccination_centers_controller.rb
> +      @vaccination_center.media_option_at = Time.zone.now if @vaccination_center.media_option
Une autre solution pourrait être d'initialiser ces dates dans le modèle en utilisant une callback `before_save` et en testant le changement de valeur de l'option.

On pourrait également la remettre à `nil` dans le cas où l'option repasse à `false`.

2021-05-13 08:25 UTC, EmCousin commented on app/controllers/partners/vaccination_centers_controller.rb
> +      @vaccination_center.media_option_at = Time.zone.now if @vaccination_center.media_option
Il n'y a effectivement pas besoin de persister `visible_option` et `media_option` en base de données. Ce sont des informations doublons avec `visible_option_at` et `media_option_at` qui risquent d'apporter des problèmes de maintenance à terme.

On peut régler ce problème en définissant `visible_option` et `media_option` en `attr_accessors` et utiliser une callback `before_save` ou `before_validation` comme le propose @genezys

2021-05-16 09:54 UTC, carsso commented
Je pense que @peiofour n'a pas eu le temps, a voir si quelqu'un va pouvoir reprendre #473
Je ferme la PR en attendant, vous pourrez réouvrir si besoin.

2021-05-16 09:54 UTC, closed without merging