Ajout d'une page de statistiques basique, qui pourra être enrichie au fur et à mesure des idées
hostolab/covidliste pull request #629
Opened 2021-04-28 10:41 UTC by Bartimeux

Bonjour,
Par curiosité, j'avais envie de remonter quelques stats de l'application. Simple curieux et passionné de stats (j'ai fait partie de la première promo' de la formation dont sort Guillaume Rozier), je suis très peu expérimenté en dev' Web, par conséquent n'hésitez pas à me faire des retours un peu détaillés (je me suis spécialisé dans l'architecture & l'admin' sys') sur ce qui manque/ce qu'il faut changer.
Bonne journée !

2021-04-28 14:48 UTC, navidemad commented
@users avec plusieurs centaines de milliers de rows, faire un .each dessus et des traitements c'est se tirer une balle dans le pied en terme de cout d'utilisation, et je pense que deployer en prod ta page se verra en timeout tout le temps. On affiche déjà les stats sur une nouvelle homepage qui est en cours de construction. Mais merci pour ta contribution, l'idée de l'age moyen est peut-être une piste plus abordable mais fait par au niveau base de donnée et mis en cache redis.

2021-04-28 15:06 UTC, Bartimeux commented
Effectivement, je me doute que la base est colossale et qu'il faudrait faire ça proprement, soit via des tables de statistiques dédiées soit via une DB plus rapide que PostGres 😃 L'idée était plus de mettre en exergue la valeur de données ;-)
Une bonne stat' à afficher également serait le nombre de matchs depuis le début de l'app, et là par contre je pense qu'il faudrait créer une table de stat (j'avais pas le courage de toucher au datamodel).
En tout cas merci pour les retours 👍

2021-04-29 05:37 UTC, carsso requested changes
Très bonne idée de faire une page de stats 👍🏻, ça rejoint des idées formulées par d'autres personnes de l'équipe 😉

Par contre pas de cette manière là, ça va exploser la base de données 💥.
Il faut bien voir qu'on est sur un volume de données important.
Ce qui marche sur ton env de dev avec quelques centaines de lignes peut exploser la base de prod si jamais on merge.

Il faut aussi qu'on fasse une passe sur l'aspect légal de l'exposition des statistiques en fonction de la version des CGV et de la politique de confidentialité au moment de leur recueil.

Je reject juste pour éviter qu'on merge ça par erreur et qu'on casse tout mais l'idée est bonne :)

2021-04-29 08:27 UTC, mathieuripert commented
> Bonjour,
> Par curiosité, j'avais envie de remonter quelques stats de l'application. Simple curieux et passionné de stats (j'ai fait partie de la première promo' de la formation dont sort Guillaume Rozier), je suis très peu expérimenté en dev' Web, par conséquent n'hésitez pas à me faire des retours un peu détaillés (je me suis spécialisé dans l'architecture & l'admin' sys') sur ce qui manque/ce qu'il faut changer.
> Bonne journée !

Merci @Bartimeux pour ta suggestion, malheureusement le traitement des données personnelles des utilisateurs de Covidliste est soumis à des CGUS (https://www.covidliste.com/cgu_volontaires) mais ne nous permettent pas de faire ce genre de statistiques avec les utilisateurs inscrits avant le 20 avril.

2021-04-29 10:15 UTC, rchampourlier commented
Bonjour à tous ! Au vu des commentaires, désolé @Bartimeux mais on va fermer la pull-request. Je fais le bad guy mais c'est pour garder notre liste de PRs clean ;) 

Merci bcp pour ta suggestion en tous cas et n'hésite pas à proposer des changements sous forme d'issue aussi, pour lancer la discussion avant de te mettre au code si tu veux !

2021-04-29 10:15 UTC, closed without merging