Feature/enforce campaign validation on same day
hostolab/covidliste pull request #799
Opened 2021-05-17 11:04 UTC by EmCousin

Fixes https://github.com/hostolab/covidliste/issues/778

## Résumé

This Pull Request adds validation rules on the backend to ensure that a campaign is valid:
- Ensures a campaign's `starts_at` attribute is at least 10 minutes the future on creation
- Ensures a campaign's `ends_at` attribute is at least 15 minutes after `starts_at`
- Ensures both `starts_at` and `ends_at` share the same day

## Détails

Most of these backend validaiton rules where already implemented frontend-side. We're merely enforcing them backend side.

## Additional Notes

- This Pull Request implements a re-usable DatetimeValidator. It made sense to build one because of just how many time-based validation rules we have on the Campaign model.
- There were conflicts in I18n translations between `fr.yml` and `devise.fr.yml`. This Pull Request fixes those and leaves `devise.fr.yml` with translations that are strictly related to Devise.
- Tests have been adapted to match the validation rules

2021-05-18 21:12 UTC, mathieuripert commented on app/models/campaign.rb
> +  validates :starts_at, datetime: {later_than: proc { 10.minutes.from_now }}, on: :create
je ne suis pas certain qu'on ait besoin d'un validation sur `starts_at` ici et meme il se peut que `starts_at` soit < 10 `minutes from now` car il peut se passer qq minutes entre le moment ou la personne ouvre le formulaire et le valide.

2021-05-19 06:23 UTC, mathieuripert requested changes
Not sure about the validation on `starts_at`

2021-05-19 07:19 UTC, EmCousin commented on app/models/campaign.rb
> +  validates :starts_at, datetime: {later_than: proc { 10.minutes.from_now }}, on: :create
La validation existe côté frontend, mais effectivement je n'ai pas pris en compte le laps de temps. On pourrait à tout le moins changer `10.minutes.from_now` par `Time.current` ?

2021-05-19 08:42 UTC, mathieuripert commented on app/models/campaign.rb
> +  validates :starts_at, datetime: {later_than: proc { 10.minutes.from_now }}, on: :create
Oui mais en vrai cette validation même front end n est pas vraiment nécessaire donc je serais pour ne pas l avoir du tout coté backend

2021-05-20 06:45 UTC, mininao commented
Hello @EmCousin ! Je viens de voir ce sujet, en fait il me semble que le problème se situe côté front, où je crois qu'on ne vérifie pas que l'horaire de début est le même jour que l'horaire actuel.

Il n'est normalement pas possible de soumettre le formulaire autrement qu'en passant par le JS, et donc avec la logique de validation, et je ne pense pas qu'un centre ait crafté une requête à la main avec des mauvais horaires 😁

2021-05-20 07:00 UTC, mininao commented on app/models/campaign.rb
> +  validates :ends_at, datetime: {earlier_than: proc(&:end_of_day), message: :same_day}
:end_of_day est dans quelle timezone ? Est-ce qu'il y a un risque que end_of_day sur le serveur soit à 22h, ou 20h heure utilisateur, et qu'on bloque alors que c'est ok ?

2021-05-20 07:05 UTC, mininao commented
(Je viens de tester, et si tu mets ton heure locale à 22h, le front t'autorise bien à créer une campagne demain.)

2021-05-20 09:23 UTC, EmCousin commented
@mininao je veux bien que tu t'en occupes si tu as un peu de temps aujourd'hui 🙏 sinon je m'en occupe demain

2021-05-20 13:32 UTC, mininao commented
Je vais pas avoir le temps aujourd'hui hélas, si tu peux le faire demain c'est fantastique, merci beaucoup !

2021-05-22 07:13 UTC, mininao commented
Validation front faite ici : https://github.com/hostolab/covidliste/pull/837

2021-05-23 12:08 UTC, EmCousin commented on app/models/campaign.rb
> +  validates :ends_at, datetime: {earlier_than: proc(&:end_of_day), message: :same_day}
end_of_day est dans la timezone de l'application Rails, qui n'est pas explicitement définie, et est donc par défaut égale à celle du système. Donc probablement Europe/Paris vu qu'on héberge l'app dans un datacenter de cette région

2021-05-23 15:37 UTC, EmCousin commented
Je passe cette PR en draft car je vais la retravailler pour prendre en compte les fuseaux horaires (cf. https://github.com/hostolab/covidliste/pull/862)

2021-06-07 07:42 UTC, closed without merging