[DRAFT] Create confirmation sms
hostolab/covidliste pull request #839
Opened 2021-05-22 00:06 UTC by pducolin

Fixes #807 

## Résumé

Simplifier la gestion des centres et rassurer les utilisateurs grâce à un sms récap suite à la confirmation d'un match. Inspiré par https://github.com/hostolab/covidliste/pull/783

## Détails

- Création du Job SendConfirmedMatchSmsJob
- Ajout de la colonne :confirmed_sms_sent_at à Match
- Création du spec

2021-05-22 19:50 UTC, colinemarie commented on app/jobs/send_confirmed_match_sms_job.rb
> +      match.update(confirm_sms_sent_at: Time.now.utc, confirm_sms_provider: provider, confirm_sms_provider_id: sms_provider_id)
comme tu le disais dans ton comment je mettrais plutôt `confirmed_sms_sent_at`

2021-05-22 19:50 UTC, colinemarie commented on app/jobs/send_confirmed_match_sms_job.rb
> +  queue_as :critical
est-ce qu'on ne le mettrait pas en `mailers` comme le `SendConfirmedMatchEmail` ?

2021-05-23 07:14 UTC, mathieuripert commented on db/migrate/20210523033232_add_confirmed_sms_sent_at_to_matches.rb
> +    add_column :slot_alerts, :confirmed_sms_sent_at, :datetime
```suggestion
    add_column :matches, :confirmed_sms_sent_at, :datetime
```

2021-05-23 07:15 UTC, mathieuripert commented on db/migrate/20210523033810_add_confirmed_sms_provider_information_to_matches.rb
> +    return unless Match.last
Selon moi on a pas besoin de ce backfill ici car la colonne n'existe pas encore

2021-05-23 16:39 UTC, mathieuripert requested changes
cf my comments

2021-05-24 16:21 UTC, pducolin commented
Cleaned up et refactored dans https://github.com/hostolab/covidliste/pull/870

2021-05-24 16:21 UTC, closed without merging