Ajout d'une confirmation si un centre de vaccination est déjà existant
hostolab/covidliste pull request #985
Opened 2021-06-14 17:50 UTC by MaxenceLenoir

Fixes #915

## Résumé

Apparition d'un warning au dessus du form de création si un (ou plusieurs) centre de vaccination possédant la même adresse ou le même nom existe déjà.
Si l'utilisateur souhaite tout de même créer le centre, confirmation via une checkbox.

## Détails

Ajout d'une variable d'instance `@same_existing_vaccination_centers` dans la méthode create du `VaccinationCentersController`.

La méthode privée `check_if_already_exists` permet de stocker dans cette variable un tableau qui répertorie les informations nécessaires (à savoir `:name` et `:address`) (Elle retourne `false` si pas de correspondance).
Cette méthode est facilement paramétrable et peut prendre en compte d'autres attributs si nécessaire.

Dans la vue, on retourne un warning + une checkbox supplémentaire dans le form en fonction de la valeur de cette variable.
Le warning reprend les noms / adresses de tous les centres de vaccination stockées dans la variable.
Pour confirmer la création, l'utilisateur est alors obligé de cocher la checkbox "Je confirme vouloir créer ce centre".

## Avant

Aucun message d'alerte -> Création du centre de vaccination

## Après

![image](https://user-images.githubusercontent.com/60671940/121935089-70327500-cd1e-11eb-9dea-7b782107af80.png)

2021-06-15 23:17 UTC, carsso commented
Merci pour cette PR @MaxenceLenoir 🎉

Peux-tu faire quelques petits changements STP  : 
- Faire le check de la comparaison sur les champs suivants : `:address, :phone_number, :finess`
- Afficher les propositions de centres similaires sous la forme : `Nom du centre - Adresse`
- Rendre la case à cocher non required pour qu'on puisse changer des infos du formulaire et le renvoyer sans la cocher (pour que ça relance une recherche).
- Déplacer la zone jaune pour que la case à cocher soit dedans, c'est plus logique (actuellement elle est au dessus de la zone de la liaison Pro Santé Connect, c'est curieux).

Si tu as du temps et que tu veux nous rejoindre sur le Slack, n'hésite pas à me le dire et je t'inviterai.

2021-06-15 23:18 UTC, carsso requested changes
cf https://github.com/hostolab/covidliste/pull/985#issuecomment-861895049

2021-06-16 18:52 UTC, MaxenceLenoir commented
@carsso, j'ai repushé en prenant en compte les 4 modifications souhaitées.

Et sinon, j'ai un peu de temps en ce moment donc je veux bien rejoindre le slack du projet.
Merci.

2021-06-18 15:11 UTC, carsso approved these changes

2021-06-18 15:11 UTC, merged